### ISSUE TITLE
Track AxiDraw status & automatically reconnect

### ISSUE THREAD

**Issue by kylestetz** [nornagon/saxi#1]
Unless I'm mistaken the server only connects to the AxiDraw once at startup, so e.g. canceling a plot and unplugging the power (to re-zero the machine) drops the connection and requires restarting the server and refreshing the UI.

It would be nice to 1) automatically reconnect, maybe by polling while disconnected, and 2) display the connection status in Saxi, so that the UI can be a little more resilient.

<img width="670" alt="screen shot 2019-01-20 at 10 58 31 am" src="https://user-images.githubusercontent.com/2008156/51443728-594cdd00-1ca2-11e9-9650-d8a6cec5520c.png">

**Comment by nornagon** [comment]
You shouldn't need to unplug the power to re-zero the machine (that's what the "limp" button does), but I agree we should auto-reconnect to the serial port.

Also, it's kind of a separate issue, but the UI currently only opens the socket to the server one time, so if you close your laptop & re-open it then you'll be disconnected from the axidraw & have to refresh to reconnect & get status. ("plot" and "cancel" will still work as they issue POST requests, but penup/pendown won't.)

I'll open a new issue for the UI reconnection.

**Comment by nornagon** [comment]
@kylestetz this could use some nice UI to indicate the connection status. As is there's no way in the UI you can know if the robot's connected or not other than by hovering the 'saxi' logo and seeing if it has a tooltip like `/dev/tty.usbmodem14421`
