### ISSUE TITLE
Raster/Fill Feature

### ISSUE THREAD

**Issue by HenrySkup** [nornagon/saxi#100]
I know that this may be a departure from the core functionality, but as I think it would be useful and is included in the Axidraw Inkscape extension I think it has merit.

Basic idea would be to include ways to "fill in" or raster over areas. (i.e. https://wiki.evilmadscientist.com/Creating_filled_regions)

I could see this plug into #69 perhaps.

It would be good to have basic (back and forth) as well as circular and spiral rastering (though to start off with using the inkscape extension as a bench mark would be more than enough)

It would be cool if there was an ability to plug in a custom rastering routine too (though I have no idea what the best way to accomplish this would be).

----

Something interesting algo wise: https://engineerdog.com/2021/08/18/optimal-path-planning-and-hatch-filling-for-pen-plotters/

**Comment by nornagon** [comment]
While cool, I think filling shapes is much too complicated for saxi. Filling is best done as a preprocessing step over which you'll have much better control than saxi could provide.
