### ISSUE TITLE
0.15.0 is broken on RPI 4 + Axidraw A3

### ISSUE THREAD

**Issue by ostwilkens** [nornagon/saxi#131]
My plotter freezes and makes horrifying noises with the latest version. 
Not sure if it's related but looks like there is an insane amount of network traffic between my rpi and client computer during plotting. 
Things work fine in 0.14.0.

**Comment by jimmykl** [comment]
+1 on this – I stopped using saxi because it sounds like it's going to trash my machine (0.15.0 on Pi 3 Model B+ with Axi SE/A3) It will draw a few lines, stutter and hung for seconds at a time but most concerningly, as above, sometimes have spasms on travel moves which sound like it'll break the machine

**Comment by edouard-gillet** [comment]
I had the same issue on a Raspberry Pi 4, everything was fine in 0.14.0 and started having issues with stuttering and hanging after upgrading to 0.15.0.
I checked the different commits and figured it was most likely due to the change to drive Axidraw over WebSocket #63.
I kept 0.15.0 and rolled back that commit and it solved the issue for me.
I did not investigate further why the WebSocket change was causing stuttering issue on the Raspberry Pi.

**Comment by alexrudd2** [comment]
Confirmed with `0.15.0` on an M1 Mac.

The individual commands to the pen up/down work fine, but trying to plot sends the motors into horrible spasms until I pull the plug.

**Comment by alexrudd2** [comment]
OK the grinding improves with rehoming, but there is still something strange happening.  There are a huge amount of connect and disconnect messages (when killing the server) as compared to `0.14.0`

`0.14.0`: Notice no duplicate "connect" messages, and the "disconnected" messages are every 5s.
<img width="548" alt="Screenshot 2023-06-30 at 8 01 45 PM" src="https://github.com/nornagon/saxi/assets/52292902/b80ccad3-0ed2-44ea-ad11-9469a057188b">

`0.15.0`: Notice the duplicate "connect" messages (varies), and the "disconnected" messages occur many times per second.
<img width="550" alt="Screenshot 2023-06-30 at 7 59 34 PM" src="https://github.com/nornagon/saxi/assets/52292902/84f58a17-bd9a-4dce-b928-ffb14c28d0aa">

**Comment by julienes** [comment]
I've just reinstalled version 0.15, which I had uninstalled last time because of this problem, and I see that it's still there. I've just installed it to be able to use the new brushless servo. Any news about this problem?

**Comment by alexrudd2** [comment]
`0.15` doesn't include code for the brushless yet, and the dev is pretty busy with a newborn right now.

You can try installing from one of the forks, where we're experimenting before trying to merge here.
- https://github.com/alexrudd2/saxi/tree/brushless
- https://github.com/jedahan/saxi/tree/brushless-v2

**Comment by julienes** [comment]
Oh ok, I'll take a look. I did that https://github.com/nornagon/saxi/issues/136 and now I can control my brushless with Saxi. But I have the problem of the Axidraw freezing during the plot

**Comment by oskay** [comment]
> Oh ok, I'll take a look. I did that #136 and now I can control my brushless with Saxi. But I have the problem of the Axidraw freezing during the plot

You might be able to revert to the earlier Saxi version that wasn't freezing for you (if there is one), and then "manually" apply the patches from #136.

**Comment by julienes** [comment]
Thank you! I've changed it back to version 0.14.0. I tried yesterday but it didn't seem to work when I changed the files to the new ones. I changed the lines manually and it works. Glad to be able to continue using Saxi.

**Comment by jedahan** [comment]
@osresearch i think this is it

**Comment by jedahan** [comment]
Regarding the many listeners, i wonder if these lines shoule be ported https://github.com/nornagon/saxi/commit/593c451e8ba252b1e85f27c373df8c2aa621b723?diff=split#diff-8a8ae07582c9d433ec8c2e5c4310ff8901e604f4965c5b90a49117ad46c47595L236-L247

**Comment by jedahan** [comment]
I manually 'reverted' the commit with webserial, and things are working smoothly.

Would be great to get webserial back in and working at a future point.
