### ISSUE TITLE
Bug: disabling 'fit page' does not respect SVG scale

### ISSUE THREAD

**Issue by abey79** [nornagon/saxi#42]
Consider the following  SVG as seen in InkScape:
![unknown](https://user-images.githubusercontent.com/49431240/75170544-8fbd1d00-572a-11ea-9959-305403875175.png)
Once loaded in saxi, the scale is clearly not respected:
![unknown-2](https://user-images.githubusercontent.com/49431240/75170548-921f7700-572a-11ea-9cec-3caf31521b2f.png)

Here is the SVG file: [vader_10cm_opt.svg.zip](https://github.com/nornagon/saxi/files/4245587/vader_10cm_opt.svg.zip)

It may be that the `width` and `height` attributes of the `svg` tag are not considered. (Note that in this present SVG, the `viewBox` attribute is omitted, but should be honoured as well.)

**Comment by abey79** [comment]
FWIW, [here is](https://github.com/abey79/vpype/blob/09e0ef5fb298556fc6fecc8381042b911d0fd203/vpype/read.py#L43) how I do it in vpype. I'm using SVG pixels (1/96th of an inch) internally, thus the scale factor of 1 when `viewBox` is omitted. You'll need some further scaling for whatever units you are using internally.

**Comment by nornagon** [comment]
Should be fixed by 05b0b7b, will release shortly. Not sure yet if it correctly handles viewbox, but your test svg seems to work correctly at least!
