### ISSUE TITLE
Save pen & paper configuration to localStorage

### ISSUE THREAD

**Issue by kylestetz** [nornagon/saxi#5]
The pen and paper settings should be sticky so you don't need to reconfigure them on every page load.

The downside with a basic implementation is that you can't restore your custom settings if you decide to do a weird plot and want to go back. In the future this could be handled with a manual "save as defaults"-type button.

**Comment by blakedietz** [comment]
Just a heads up. I've started working on this. I'll submit a pr asap.

**Comment by nornagon** [comment]
Great, let me know if you run into any troubles :)

**Comment by nornagon** [comment]
Closed by 3484ad94dd2341bfab09f2a4561e1f6e25cba51b
