### ISSUE TITLE
Triggering plot twice causes loud noises and weird behaviour

### ISSUE THREAD

**Issue by jvolker** [nornagon/saxi#57]
I've been able to press "plot" twice, while the Raspberry Pi 3B+ was apparently getting ready to start the plot. The plotter started making strange loud sounds and made jerking movements which didn't sound/look healthy.

Would be good if the "plot" button would be disabled while starting the plot.

**Comment by nornagon** [comment]
Good catch, thanks for the report! I fixed the issue on the backend side, so it should no longer be possible to have multiple "plot" requests at the same time.
