### ISSUE TITLE
0 radius circles only work when "fit page" selected

### ISSUE THREAD

**Issue by HenrySkup** [nornagon/saxi#70]
Hi, I'm trying to plot points (pen down + delay + pen up ).  Saxi seems to be able to at least do the pen down + pen up motion when given `<circle>`s with `r=0`.  However it is only generating a plan when the "fit page" option is selected.  When this is deselected, the preview disappear (i.e. no travel paths) and nothing plots.

**Comment by Stanko** [comment]
I wasn't aware you could plot circles with `r=0`. What I usually do is to generate a super short path, something like:
```js
`<path d="M ${ p.x } ${ p.y } H 0.01" />`
````
which draws a horizontal line, but it is short enough to plotted as a dot. 

This works with saxi and with the official inkscape plugin. Hope that helps!

**Comment by nornagon** [comment]
@HenrySkup would you be able to attach an SVG that exhibits the issue you're encountering?

**Comment by HenrySkup** [comment]
@nornagon 

Here are the SVGs :
[Archive.zip](https://github.com/nornagon/saxi/files/5627681/Archive.zip)

**Notes**
Made with SVG.js, saved via [d3-save-svg](https://github.com/edeno/d3-save-svg)

**Comment by HenrySkup** [comment]
I think this has been resolved.  Just did a plot yesterday with the latest version and was able to plot a grid of "dots"

**Comment by nornagon** [comment]
Glad to hear it!
