### ISSUE TITLE
can saxi run on windows?

### ISSUE THREAD

**Issue by kevin227227** [nornagon/saxi#81]

**Comment by nornagon** [comment]
have you tried it? :)

**Comment by kevin227227** [comment]
I tried it but I didn't know how to execute it, sorry I'm not very good with these things.

**Comment by nornagon** [comment]
It's beyond the scope of this project to describe how to install and use Node.js on Windows, but you might try the bundled app: https://github.com/nornagon/saxi-app/releases

the app is still experimental, so it might not work, but you won't have to install anything!
