### ISSUE TITLE
Help setting up new servo

### ISSUE THREAD

**Issue by jimmykl** [nornagon/saxi#82]
I have installed a servo which reverses the axidraw's up/down controls

Plots work ok by swapping the up/down % in saxi's ui but when the plot finishes the final move is done with the pen down and I get a line drawing back to the home position over the plot 😢 

I've got a dev build running but can't follow the code well enough to see where the pen height during the final move is controlled

I thought it could be in `server.ts` and tried adding `ebb.setPenHeight(Device.Axidraw.penPctToPos(100), 1000);` in a few places (`realPlotter` and the `doPlot` function) but to no effect and I'm really just shooting blind

It would be great if someone could point me in the right direction!

**Comment by jimmykl** [comment]
Found it (in `planning.ts` `plan`)

**Comment by nornagon** [comment]
Oh dear! I'm glad you figured it out. Do you think it would be broadly useful to have a checkbox to reverse servo direction in the options? Or is this particular to your individual setup?

**Comment by jimmykl** [comment]
I think it's probably too much of an edge case to expose in the UI.

Unless there was an 'advanced: only change these if you're sure you need to' type of section?

**Comment by nornagon** [comment]
Alrighty, let's leave it then :)
