### ISSUE TITLE
windows 10

### ISSUE THREAD

**Issue by kevin227227** [nornagon/saxi#83]
Can anyone give me instructions on how to install saxi on windows 10 ?

**Comment by nornagon** [comment]
Duplicate of #81

**Comment by nornagon** [comment]
Hi there, please don't open new issues when existing ones are closed. Instead, continue conversation on the original issue.

Thanks!

**Comment by kevin227227** [comment]
hello, sorry, I thought that as it said "closed topic" no one was answering it, I am new and did not know, sorry.
