### ISSUE TITLE
Make pen height at the end of a plot configurable

### ISSUE THREAD

**Issue by EmmaSimon** [nornagon/saxi#87]
On my iDraw plotter, every time a plot finishes, instead of raising the pen and returning home, it instead presses the pen down much harder into the paper than it's configured to, and returns to home.

This seems to be the result of a reversed pen servo, and a fix for it was made on @jimmykl's fork here: https://github.com/jimmykl/saxi/commit/81c7872fb0ab89e016ee9c7b009e7c081e069c62

It might make sense to make the final up height configurable for general issues with different plotters and servos, rather than hard coding it to 0.

You can see this in the attached images, in the first one it's the line through the 2deg and 1mm circles. It didn't leave a mark because it pressed hard enough to bend the nib sideways. In the other one, it left a deep gouge in the paper, it was pressing significantly harder than the setting for the regular strokes.

![contactsheet](https://user-images.githubusercontent.com/12971446/122857330-4e209000-d2e6-11eb-99be-0f63e13c5a36.jpg)![cubes](https://user-images.githubusercontent.com/12971446/122857333-4fea5380-d2e6-11eb-8c8a-ba79cd063a43.jpg)

_Originally posted by @EmmaSimon in https://github.com/nornagon/saxi/issues/86#issuecomment-865497479_

**Comment by nornagon** [comment]
Would it make sense to check the "polarity" of the up/down heights that are already configured in the UI, and go to either 0% or 100% depending on which way "up" is?

i.e. if up < down, go to 0%, otherwise go to 100%?

**Comment by EmmaSimon** [comment]
Ahh, yeah I like that, that should work well! Definitely would prefer to avoid a config if possible.

**Comment by nornagon** [comment]
@EmmaSimon give 0.14.0 a whirl!

**Comment by jimmykl** [comment]
@nornagon this works for me 🙏

**Comment by EmmaSimon** [comment]
Yep, that works! Thanks so much 🎉

**Comment by nornagon** [comment]
FYI, I opened https://github.com/nornagon/saxi/issues/90 to track some additional changes that are needed to fully support this. So be aware, you might run into issues when pausing/canceling, or altering pen heights in a plan.
