### ISSUE TITLE
Feature request: cancel plot confirmation dialog

### ISSUE THREAD

**Issue by jimmykl** [nornagon/saxi#92]
It would be cool to have an 'are you sure you want to cancel the plot' confirmation dialog on 'cancel plot' button. 

Not that I accidentally pressed it instead of 'resume plot' in the middle of a long plot 👀

**Comment by HenrySkup** [comment]
FYI : https://css-tricks.com/choice-words-about-the-upcoming-deprecation-of-javascript-dialogs/

**Comment by jimmykl** [comment]
Sigh. I’ll just relocate the button.

**Comment by jimmykl** [comment]
That would do the trick! 

Perhaps the text could change to 'Click again to confirm' to make the ux clear? Save people posting an issue that it doesn't work with one click!

**Comment by nornagon** [comment]
Yep, seems reasonable! Anyone want to have a go at implementing this?
